### ISSUE TITLE
[electron-builder] symlink issue when bundling dugite

### ISSUE THREAD

**Issue by kittaakos** [desktop/dugite#140]
I have problems when I am trying to bundle my electron application with `dugite`. I do not know whether this is a `dugite` issue or an `electron-builder` one.

I have forked a boilerplate electron application and added `dugite` as a dependency. It works as expected when I start the application from the source with: `npm i && npm start`.

The problem occurs when I am bundling it. As I see, [ASAR does not handle symlinks properly](https://github.com/electron-userland/electron-builder/issues/1376), so I have configured [`"asar": false`](https://github.com/kittaakos/electron-boilerplate/commit/bd87ecac7cced0780d938cc09601b0b567cb99c9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). When I am running my bundler task with `npm run release`, it does not fail but it logs the following error. Is it safe to just ignore it?

```
Unhandled rejection Error: ENOENT: no such file or directory, symlink 'git' -> '/Users/akos.kitta/Desktop/electron-boilerplate/dist/mac/Electron.app/Contents/Resources/app/node_modules/dugite/git/libexec/git-core/git-check-ignore'
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/util/appFileCopier.ts:70:38
From previous event:
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/util/appFileCopier.ts:70:21
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at copyAppFiles (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/out/util/appFileCopier.js:62:21)
    at taskManager.addTask.default.each.it (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/platformPackager.ts:238:86)
From previous event:
    at MacPackager.copyAppFiles (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/platformPackager.ts:238:43)
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/platformPackager.ts:186:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at MacPackager.doPack (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/out/platformPackager.js:267:11)
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/macPackager.ts:87:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/out/macPackager.js:183:11)
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/out/packager.js:332:11)
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/out/packager.js:261:11)
    at /Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/out/builder.js:63:21)
    at then (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/electron-boilerplate/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Probably you have quite good experience with both electron and dugite after putting `GitHub Desktop` together, so I thought, it worth asking here.

Steps to reproduce:
```bash
mkdir electron-dugite-tmp \
&& cd electron-dugite-tmp \
&& git clone https://github.com/kittaakos/electron-boilerplate.git \
&& cd electron-boilerplate \
&& npm i \
&& npm run release 
```

Thank you!

**Comment by shiftkey** [comment]
This isn't a `dugite` issue, but is probably related to how `electron-builder` is trying to optimize files which are symlinks:  https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/util/appFileCopier.ts

We don't use `electron-builder` on Desktop - we just splat the files into the directory so the symlinks are preserved - so I'm not quite sure how to tell `electron-builder` to ignore these paths.

**Comment by kittaakos** [comment]
Thank you for the feedback! If you do not mind, I will leave this ticket open for a while here, and once I figure out a solution/workaround, I will close this issue with some additional information.

**Comment by shiftkey** [comment]
I'm going to close this out because it's already being tracked upstream.

@kittaakos feel free to drop a comment in here if you find a resolution for the issue.

**Comment by kittaakos** [comment]
Does not happen anymore with `electron-builder version=19.56.2`.
