### ISSUE TITLE
npm install fails when behind a proxy

### ISSUE THREAD

**Issue by MartinBenninger** [desktop/dugite#148]
Installing the dugite package from npm fails on Windows. It works fine on Linux though.

It seams to be an error with how the checksum is being calculated in the `download-git.js` script. I have checked and the expected checksum matches what is posted on the [dugite-native releases page](https://github.com/desktop/dugite-native/releases).

Here is the console output when attempting to install v1.49.0
```
PS H:\> npm install dugite

> dugite@1.49.0 postinstall H:\node_modules\dugite
> node ./script/download-git.js

Validation failed. Expected 'a54b64be0976c3f919a52d4dd6dcfb9434744072860df980767d662275a9f235' but got 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.15.0-rc1/dugite-native-v2.15.0-win32
-25.tar.gz
Error raised while downloading https://github.com/desktop/dugite-native/releases/download/v2.15.0-rc1/dugite-native-v2.1
5.0-win32-25.tar.gz { Error: connect ETIMEDOUT 192.30.253.113:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.113',
  port: 443 }
npm WARN enoent ENOENT: no such file or directory, open 'H:\package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dugite@1.49.0 postinstall: `node ./script/download-git.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dugite@1.49.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\z0039cjb\AppData\Roaming\npm-cache\_logs\2017-11-17T08_36_18_434Z-debug.log
```

It also happens with v1.48.0
```
PS H:\test> npm install dugite@1.48.0

> dugite@1.48.0 postinstall H:\test\node_modules\dugite
> node ./script/download-git.js

Validation failed. Expected 'db14ddc1281606b001a44b70f2fc3deda6e60686de06d135056205216c2a5663' but got 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.14.3-rc1/dugite-native-v2.14.3-win32
-23.tar.gz
Error raised while downloading https://github.com/desktop/dugite-native/releases/download/v2.14.3-rc1/dugite-native-v2.1
4.3-win32-23.tar.gz { Error: connect ETIMEDOUT 192.30.253.113:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.113',
  port: 443 }
npm WARN enoent ENOENT: no such file or directory, open 'H:\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dugite@1.48.0 postinstall: `node ./script/download-git.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dugite@1.48.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\z0039cjb\AppData\Roaming\npm-cache\_logs\2017-11-17T08_43_27_174Z-debug.log
```

I haven't tested with older versions.

I ran into this problem when installing the npm packages needed for [GitHub Desktop](https://github.com/desktop/desktop) on my Windows 7 x64 machine. I later tried this on my Ubuntu 17.10 x64 setup and it installed without errors.

**Comment by MartinBenninger** [comment]
I just found this issue desktop/dugite-native#62 where the @seriouz seams to have the same problem.

**Comment by kittaakos** [comment]
@MartinBenninger, I have just tried it on my Windows 10 image, and it worked for me.
```
$ mkdir dugite-tmp && cd dugite-tmp && node --version && npm --version && npm init -y && npm i -S dugite
v8.7.0
5.4.2
Wrote to C:\Users\kittaakos\dev\dugite-tmp\package.json:

{
  "name": "dugite-tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



> dugite@1.49.0 postinstall C:\Users\kittaakos\dev\dugite-tmp\node_modules\dugite
> node ./script/download-git.js

Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.15.0-rc1/dugite-native-v2.15.0-win32-25.tar.gz




npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN dugite-tmp@1.0.0 No description
npm WARN dugite-tmp@1.0.0 No repository field.

+ dugite@1.49.0
added 75 packages in 19.187s
```

**Comment by MartinBenninger** [comment]
I guess this is a proxy issue then. I am currently behind a corporate proxy but I was at home (no proxy) when I ran it on Linux.

I have configured my proxy with npm and don't have issues downloading or installing other packages. My guess is that the `download-git.js` script is attempting to download something without using the proxy configuration.

Is there a way that I could configure the proxy for the download script?

**Comment by MartinBenninger** [comment]
OK, so I set the `http_proxy` and `https_proxy` environment variables and the install worked. :raised_hands:

It might be a good idea to add this info to the docs / error message. Maybe this will help someone in the future.

**Comment by shiftkey** [comment]
If someone wants to refine the error message, this is the code to change:

https://github.com/desktop/dugite/blob/397664cba29bd0a54c44be6b44e46a5589e7845f/script/download-git.js#L62-L65

To handle the `ETIMEDOUT` message better you could write something like this:

```js
req.on('error', function (error) {
  if (error.message.code === 'ETIMEDOUT') {
    console.log(`A timeout has occurred while downloading '${config.source}' - check your internet access and try again`, error)
  } else {
    console.log(`Error raised while downloading ${config.source}`, error)
  }

  process.exit(1)
})
```
