### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by kittaakos** [desktop/dugite#177]
This is rather a question; what should I do to be able to execute the tests without failure on Windows? Everything works fine on OS X, and as I see, the AppVeyor builds were passing for both closed and currently opened PRs. It fails locally. It seems I have a different error message on Windows than the expected on. See full output:

```
kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/dugite (master)
$ git rev-parse --short HEAD && node --version && npm --version && npm run test
5f8c518
v8.7.0
5.4.2

> dugite@1.61.0 test C:\Users\kittaakos\dev\dugite
> npm run test:fast && npm run test:slow && npm run test:external


> dugite@1.61.0 test:fast C:\Users\kittaakos\dev\dugite
> cross-env LOCAL_GIT_DIRECTORY=./git/ mocha --require ts-node/register test/fast/*.ts test/auth/*.ts



  commit
    √ can commit changes (244ms)

  config
    √ sets http.sslBackend on Windows (43ms)

  environment variables
    √ can set them (50ms)
    √ when GIT_EXEC_PATH environment variable is *not* set, it will be calculated
    √ when GIT_EXEC_PATH environment variable is set, that will be used as is

  git-process
    √ can launch git (47ms)
    exitCode
      √ returns exit code when folder is empty (47ms)
      √ handles stdin closed errors (38ms)
      diff
        √ returns expected error code for initial commit when creating diff (164ms)
        √ returns expected error code for repository with history when creating diff (225ms)
        √ throws error when exceeding the output range (505ms)
    errors
      √ raises error when folder does not exist
      √ can parse errors
      √ can parse bad revision errors
      √ can parse unrelated histories error
      √ can parse GH001 push file size error
      √ can parse GH002 branch name error
      √ can parse GH003 force push error
      √ can parse GH005 ref length error
      √ can parse GH006 protected branch push error
      √ can parse GH006 protected branch force push error
      √ can parse GH006 protected branch delete error
      √ can parse GH006 required status check error
      √ can parse GH007 push with private email error
      √ can parse LFS attribute does not match error
      √ can parse rename Branch error

  lfs
    √ can be resolved (74ms)
    √ matches the expected version (70ms)

  status
    √ lists untracked file (122ms)

  stdin
    √ can write large buffers (121ms)
    √ can write strings
    √ can write strings with encoding (83ms)
    √ assumes utf-8 for stdin by default


  33 passing (2s)


> dugite@1.61.0 test:slow C:\Users\kittaakos\dev\dugite
> cross-env LOCAL_GIT_DIRECTORY=./git/ mocha -t 20000ms --require ts-node/register test/slow/*.ts test/auth/*.ts



  git-process
    clone
      1) returns exit code and error when repository doesn't exist
      √ returns exit code and error when repository requires credentials (1092ms)
      √ returns exit code when successful (905ms)
    fetch
      2) returns exit code and error when repository doesn't exist
      √ returns exit code and error when repository requires credentials (1234ms)
      √ returns exit code when successful (1094ms)
    checkout
      √ runs hook without error (284ms)

  GitProcess.spawn
    √ can launch git (39ms)
    √ returns expected exit codes (42ms)
    √ can fail safely with a diff exceeding the string length (4107ms)


  8 passing (10s)
  2 failing

  1) git-process
       clone
         returns exit code and error when repository doesn't exist:
     AssertionError: Cloning into '.'...
remote: Not Found
fatal: unable to access 'https://bitbucket.org/shiftkey/testing-non-existent.git/': Failure when receiving data from the peer
: expected null to equal 8
      at Object.<anonymous> (test\slow\git-process-test.ts:37:24)
      at Generator.next (<anonymous>)
      at fulfilled (test\slow\git-process-test.ts:4:58)
      at <anonymous>

  2) git-process
       fetch
         returns exit code and error when repository doesn't exist:
     AssertionError: remote: Not Found
fatal: unable to access 'https://bitbucket.org/shiftkey/testing-non-existent.git/': Failure when receiving data from the peer
: expected null to equal 8
      at Object.<anonymous> (test\slow\git-process-test.ts:101:24)
      at Generator.next (<anonymous>)
      at fulfilled (test\slow\git-process-test.ts:4:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dugite@1.61.0 test:slow: `cross-env LOCAL_GIT_DIRECTORY=./git/ mocha -t 20000ms --require ts-node/register test/slow/*.ts test/auth/*.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the dugite@1.61.0 test:slow script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2018-03-27T11_04_51_880Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dugite@1.61.0 test: `npm run test:fast && npm run test:slow && npm run test:external`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the dugite@1.61.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2018-03-27T11_04_51_925Z-debug.log
```

The actual error message is:
```
remote: Not Found
fatal: unable to access 'https://bitbucket.org/shiftkey/testing-non-existent.git/': Failure when receiving data from the peer
:
```

And the expected one is:
```
fatal: repository '(.+)' not found
```

**Comment by kittaakos** [comment]
By the way, I am happy to contribute a fix, if you confirm it as a problem.

**Comment by shiftkey** [comment]
This was related to a server change from Bitbucket, and I updated these tests in #179 to not check for the expected error message. I couldn't find a public server that would serve up this error without credentials, and didn't feel like adding those to the tests, so they're put aside for now.
