### ISSUE TITLE
dugite/package.json: Unexpected end of JSON input in Electron 11 beta

### ISSUE THREAD

**Issue by linonetwo** [desktop/dugite#414]
I get this after upgraded to "electron": "^11.0.0-beta.13"

```
Uncaught Exception:
SyntaxError: Error parsing /Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/TiddlyGit.app/Contents/Resources/app.asar/node_modules/dugite/package.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:269:20)
    at readPackageExports (internal/modules/cjs/loader.js:309:15)
    at applyExports (internal/modules/cjs/loader.js:450:20)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
```

It works in electron 10.1.3 , so this probably due to some api removed.

**Comment by linonetwo** [comment]
https://github.com/electron/electron/issues/25438

**Comment by linonetwo** [comment]
As of Electron 9 we do not allow loading of non-context-aware native modules in the renderer process. This is to improve security, performance and maintainability of Electron as a project.

If this impacts you, you can temporarily set app.allowRendererProcessReuse to false to revert to the old behavior. This flag will only be an option until Electron 11 so you should plan to update your native modules to be context aware.

For more detailed information see https://github.com/electron/electron/issues/18397

**Comment by linonetwo** [comment]
This doesn't happened again after I upgrade to electron v12 beta
